inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  Exclude:
    - db/migrate/**/*
    - vendor/**/*
    - frontend/**/*
