#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# render-env.sh — Resolve 1Password secrets into a slot env file
#
# Usage: render-env.sh <environment> <slot> <api_image> <frontend_image> <build_sha> <build_ref>
#
# Writes the env file to /srv/dailywerk/compose/<env>-<slot>/.env
# ---------------------------------------------------------------------------

readonly ENVIRONMENT="${1:?Usage: render-env.sh <environment> <slot> <api_image> <frontend_image> <build_sha> <build_ref>}"
readonly SLOT="${2:?}"
readonly API_IMAGE="${3:?}"
readonly FRONTEND_IMAGE="${4:?}"
readonly BUILD_SHA="${5:?}"
readonly BUILD_REF="${6:?}"

readonly SLOT_DIR="/srv/dailywerk/compose/${ENVIRONMENT}-${SLOT}"
readonly ENV_FILE="${SLOT_DIR}/.env"

case "${ENVIRONMENT}" in
  production)
    VAULT="DailyWerk Production"
    APP_HOST="app.dailywerk.com"
    RAILS_ENV="production"
    VALKEY_DB="0"
    CACHE_NS="dailywerk:prod:cache"
    CABLE_NS="dailywerk_production"
    ;;
  staging)
    VAULT="DailyWerk Staging"
    APP_HOST="staging.dailywerk.com"
    RAILS_ENV="production"
    VALKEY_DB="1"
    CACHE_NS="dailywerk:staging:cache"
    CABLE_NS="dailywerk_staging"
    ;;
  *)
    echo "ERROR: unknown environment: ${ENVIRONMENT}" >&2
    exit 1
    ;;
esac

echo "  Resolving secrets from 1Password vault '${VAULT}'..."

# Read all secrets in one pass to minimise op invocations.
RAILS_MASTER_KEY="$(op read "op://${VAULT}/rails/master-key")"
SECRET_KEY_BASE="$(op read "op://${VAULT}/rails/secret-key-base")"
DATABASE_URL="$(op read "op://${VAULT}/database/url")"
VALKEY_URL="$(op read "op://${VAULT}/valkey/url")"
WORKOS_API_KEY="$(op read "op://${VAULT}/workos/api-key")"
WORKOS_CLIENT_ID="$(op read "op://${VAULT}/workos/client-id")"
STRIPE_SECRET_KEY="$(op read "op://${VAULT}/stripe/secret-key")"
STRIPE_WEBHOOK_SECRET="$(op read "op://${VAULT}/stripe/webhook-secret")"
STRIPE_PUBLISHABLE_KEY="$(op read "op://${VAULT}/stripe/publishable-key")"
STORAGE_ACCESS_KEY_ID="$(op read "op://${VAULT}/storage/access-key-id")"
STORAGE_SECRET_ACCESS_KEY="$(op read "op://${VAULT}/storage/secret-access-key")"
STORAGE_ENDPOINT="$(op read "op://${VAULT}/storage/endpoint")"
STORAGE_REGION="$(op read "op://${VAULT}/storage/region")"
STORAGE_BUCKET="$(op read "op://${VAULT}/storage/bucket")"
METRICS_USERNAME="$(op read "op://${VAULT}/metrics/basic-auth-username")"
METRICS_PASSWORD="$(op read "op://${VAULT}/metrics/basic-auth-password")"

mkdir -p "${SLOT_DIR}"

cat > "${ENV_FILE}" <<ENVEOF
# Auto-generated by render-env.sh — do not edit
# Environment: ${ENVIRONMENT}  Slot: ${SLOT}  Generated: $(date -Iseconds)

RAILS_ENV=${RAILS_ENV}
RAILS_LOG_LEVEL=info
RAILS_LOG_TO_STDOUT=true
APP_ENVIRONMENT=${ENVIRONMENT}

RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
SECRET_KEY_BASE=${SECRET_KEY_BASE}

APP_HOST=${APP_HOST}
CORS_ORIGINS=https://${APP_HOST}
ACTION_CABLE_ALLOWED_ORIGINS=https://${APP_HOST}

DATABASE_URL=${DATABASE_URL}
DB_POOL=10

VALKEY_URL=${VALKEY_URL}/${VALKEY_DB}
REDIS_URL=${VALKEY_URL}/${VALKEY_DB}
CACHE_NAMESPACE=${CACHE_NS}
CABLE_NAMESPACE=${CABLE_NS}

AWS_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
AWS_ENDPOINT=${STORAGE_ENDPOINT}
AWS_REGION=${STORAGE_REGION}
S3_BUCKET=${STORAGE_BUCKET}

WORKOS_API_KEY=${WORKOS_API_KEY}
WORKOS_CLIENT_ID=${WORKOS_CLIENT_ID}

STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}

METRICS_ENABLED=true
METRICS_BASIC_AUTH_USERNAME=${METRICS_USERNAME}
METRICS_BASIC_AUTH_PASSWORD=${METRICS_PASSWORD}

BUILD_SHA=${BUILD_SHA}
BUILD_REF=${BUILD_REF}

GOOD_JOB_ENABLE_CRON=true

API_IMAGE=${API_IMAGE}
FRONTEND_IMAGE=${FRONTEND_IMAGE}
ENVEOF

chmod 600 "${ENV_FILE}"
echo "  Written ${ENV_FILE}"
