#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# switch-slot.sh — Switch Nginx upstream to the target slot
#
# Usage: switch-slot.sh <environment> <target_slot>
#
# Updates the active-slot marker, regenerates the Nginx upstream config,
# validates it, and reloads Nginx.
# ---------------------------------------------------------------------------

readonly ENVIRONMENT="${1:?Usage: switch-slot.sh <environment> <target_slot>}"
readonly TARGET_SLOT="${2:?}"
readonly RUNTIME_DIR="/srv/dailywerk/runtime"
readonly SLOT_FILE="${RUNTIME_DIR}/${ENVIRONMENT}-active-slot"
readonly EDGE_PROJECT="dailywerk-edge"
readonly EDGE_COMPOSE="/srv/dailywerk/compose/edge/docker-compose.yml"
readonly NGINX_CONF_DIR="/srv/dailywerk/config/nginx"

case "${TARGET_SLOT}" in
  blue|green) ;;
  *)
    echo "ERROR: slot must be 'blue' or 'green', got '${TARGET_SLOT}'" >&2
    exit 1
    ;;
esac

readonly TARGET_PROJECT="dailywerk-${ENVIRONMENT}-${TARGET_SLOT}"

# Generate the upstream snippet that Nginx includes.
# The container names follow docker-compose project naming.
cat > "${NGINX_CONF_DIR}/${ENVIRONMENT}-upstream.conf" <<CONFEOF
# Auto-generated by switch-slot.sh — do not edit
upstream ${ENVIRONMENT}_frontend {
    server ${TARGET_PROJECT}-frontend-1:8080;
}

upstream ${ENVIRONMENT}_api {
    server ${TARGET_PROJECT}-api-1:3000;
}
CONFEOF

# Validate Nginx config before reloading.
if ! docker compose -p "${EDGE_PROJECT}" -f "${EDGE_COMPOSE}" \
     exec -T nginx nginx -t 2>&1; then
  echo "ERROR: Nginx config validation failed — aborting slot switch" >&2
  exit 1
fi

# Reload Nginx (graceful — no dropped connections).
docker compose -p "${EDGE_PROJECT}" -f "${EDGE_COMPOSE}" \
  exec -T nginx nginx -s reload

# Persist the new active slot.
echo "${TARGET_SLOT}" > "${SLOT_FILE}"

echo "  ✓ ${ENVIRONMENT} now routes to ${TARGET_SLOT}"
