upstream prod_frontend {
  server dailywerk-prod-blue-frontend-1:8080;
}

upstream prod_api {
  server dailywerk-prod-blue-api-1:3000;
}

upstream staging_frontend {
  server dailywerk-staging-blue-frontend-1:8080;
}

upstream staging_api {
  server dailywerk-staging-blue-api-1:3000;
}
