#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname postgres <<-SQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DAILYWERK_DB_APP_USER}') THEN
      EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${DAILYWERK_DB_APP_USER}', '${DAILYWERK_DB_APP_PASSWORD}');
    END IF;
  END
  \$\$;

  SELECT 'CREATE DATABASE ${DAILYWERK_PRODUCTION_DB} OWNER ${DAILYWERK_DB_APP_USER}'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DAILYWERK_PRODUCTION_DB}')
  \gexec

  SELECT 'CREATE DATABASE ${DAILYWERK_STAGING_DB} OWNER ${DAILYWERK_DB_APP_USER}'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DAILYWERK_STAGING_DB}')
  \gexec
SQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${DAILYWERK_PRODUCTION_DB}" <<-SQL
  CREATE EXTENSION IF NOT EXISTS pgcrypto;
  CREATE EXTENSION IF NOT EXISTS vector;
SQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${DAILYWERK_STAGING_DB}" <<-SQL
  CREATE EXTENSION IF NOT EXISTS pgcrypto;
  CREATE EXTENSION IF NOT EXISTS vector;
SQL
